avatar: OM3.jpg
bg-img: 277H.jpg
title: Portfolio-site
email: artist@gmail.com

# Work Section
projects:
- {name: Икона "Казанская Богородица", folder: 'proj1'}
- {name: Кольцо Ом с цитрином, folder: 'proj2'}
- {name: Икона "Николай Чудотворец", folder: 'proj3'}
- {name: Значок «Локо», folder: 'proj4'}
- {name: Икона (золото), folder: 'proj5'}
- {name: Икона СВ. Александр Невский, folder: 'proj6'}
- {name: Подвеска (эскиз), folder: 'proj7'}
- {name: Подвеска (золото), folder: 'proj8'}

# Clients Section
clients:
- {avatar: '128.jpg', name: 'Елена Кузнецова', title: 'менеджер',
quote: '<strong>Ребята,всем привет.</strong> Нужно написать алгоритм который,реализующий метод градиетного
спуска,для поиска минимальных значений функции двух переменных,по идее алгоритм
правильный,но протабулировать функцию не получается,даже значения задал начальные
для метода,но просто ниче не выводит,гугл не помог.Оператор вывода есть.', logo: '128.jpg'}
- {avatar: '129.jpg', name: 'Елена Кузнецова', title: 'менеджер',
quote: '<strong>222Ребята,всем привет.</strong> Нужно написать алгоритм который,реализующий метод градиетного
спуска,для поиска минимальных значений функции двух переменных,по идее алгоритм
правильный,но протабулировать функцию не получается,даже значения задал начальные
для метода,но просто ниче не выводит,гугл не помог.Оператор вывода есть.', logo: '129.jpg'}
- {avatar: '130.jpg', name: 'Елена Кузнецова', title: 'менеджер',
quote: '<strong>33Ребята,всем привет.</strong> Нужно написать алгоритм который,реализующий метод градиетного
спуска,для поиска минимальных значений функции двух переменных,по идее алгоритм
правильный,но протабулировать функцию не получается,даже значения задал начальные
для метода,но просто ниче не выводит,гугл не помог.Оператор вывода есть.', logo: '130.jpg'}


# Contact Section
social:
- {icon: 'twitter', link: 'http://twitter'}
- {icon: 'linkedin', link: 'http://twitter'}
- {icon: 'youtube', link: 'http://twitter'}
- {icon: 'github', link: 'http://twitter'}
